name: 网页打包高途刷题

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Environment
      run: |
        npm install -g pnpm
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Generate Config Files
      run: |
        # 自动生成 inject.js
        echo "// Auto-login script
        localStorage.hasSavedLogin = true;
        window.location.href = 'https://www.gaotu.cn/pc-exercise-tool/#/home';" > inject.js

        # 生成 pake.json
        echo '{
          "url": "https://www.gaotu.cn/pc-exercise-tool/",
          "name": "GaotuExercise",
          "width": 1200,
          "height": 800,
          "user_data_dir": "./user_data",
          "inject": ["inject.js"]
        }' > pake.json

        # 生成 package.json
        echo '{
          "scripts": {
            "build": "pake build --config pake.json"
          },
          "dependencies": {
            "pake-cli": "^2.0.0"
          }
        }' > package.json

    - name: Install Dependencies
      run: pnpm install

    - name: Build Application
      run: pnpm run build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GaotuExercise
        path: |
          target/release/GaotuExercise*
          user_data/
        retention-days: 7
